[project]
name = "jubilant-system-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "pysocks>=1.7.1",
    "requests>=2.32.5",
]
